services:
  # Apache Flink Job Manager
  jobmanager:
    image: ${FLINK_DOCKER_IMAGE:-j3signalroom/mac_flink-with_hadoop_iceberg:latest}
    ports:
      - 8081:8081
      - 9092:9092
      - 443:443
    command: jobmanager
    volumes:
      - ./java/app/build/libs:/opt/flink/apps
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - AWS_REGION=${AWS_REGION}
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
  # Apache Flink Task Manager
  taskmanager:
    image: ${FLINK_DOCKER_IMAGE:-j3signalroom/mac_flink-with_hadoop_iceberg:latest}
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 3
    volumes:
      - ./java/app/build/libs:/opt/flink/apps
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - AWS_REGION=${AWS_REGION}
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
