services:
  # Apache Flink Job Manager
  jobmanager:
    build:
      context: .
      dockerfile: linux-Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_REGION: ${AWS_REGION}
        AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    ports:
      - 8081:8081
      - 9092:9092
      - 8443:443
    command: jobmanager
    volumes:
      - /Users/jeffreyjonathanjennings/j3/code_spaces/apache_flink-kickstarter/java/app/build/libs:/opt/flink/java_apps
      - /Users/jeffreyjonathanjennings/j3/code_spaces/apache_flink-kickstarter/python:/opt/flink/python_apps
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.flamegraph.enabled: true
        web.backpressure.refresh-interval: 10000
        fs.s3a.access.key: $AWS_ACCESS_KEY_ID
        fs.s3a.secret.key: $AWS_SECRET_ACCESS_KEY
        fs.s3a.endpoint: s3.$AWS_REGION.amazonaws.com
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - AWS_REGION=$AWS_REGION
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
  # Apache Flink Task Manager
  taskmanager:
    build:
      context: .
      dockerfile: linux-Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_REGION: ${AWS_REGION}
        AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 3
    volumes:
      - /Users/jeffreyjonathanjennings/j3/code_spaces/apache_flink-kickstarter/java/app/build/libs:/opt/flink/java_apps
      - /Users/jeffreyjonathanjennings/j3/code_spaces/apache_flink-kickstarter/python:/opt/flink/python_apps
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        fs.s3a.access.key: $AWS_ACCESS_KEY_ID
        fs.s3a.secret.key: $AWS_SECRET_ACCESS_KEY
        fs.s3a.endpoint: s3.$AWS_REGION.amazonaws.com
        taskmanager.memory.task.off-heap.size: 256m
        taskmanager.memory.process.size: 2048m
        taskmanager.memory.network.fraction: 0.2
        python.fn-execution.memory.limit: 512mb
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - AWS_REGION=$AWS_REGION
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
