services:
  # Apache Flink Job Manager
  jobmanager:
    build:
      context: .
      dockerfile: linux-Dockerfile
      args:
        FLINK_LANGUAGE: ${FLINK_LANGUAGE}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_REGION: ${AWS_REGION}
    ports:
      - 8081:8081
      - 9092:9092
      - 8443:443
    command: jobmanager
    volumes:
      - /Users/jeffreyjonathanjennings/j3/code_spaces/apache_flink-kickstarter/java/app/build/libs:/opt/flink/java_apps
      - /Users/jeffreyjonathanjennings/j3/code_spaces/apache_flink-kickstarter/python:/opt/flink/python_apps
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - AWS_REGION=$AWS_REGION
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_S3_BUCKET=$AWS_S3_BUCKET
      - FLINK_LANGUAGE=$FLINK_LANGUAGE
  # Apache Flink Task Manager
  taskmanager:
    build:
      context: .
      dockerfile: linux-Dockerfile
      args:
        FLINK_LANGUAGE: ${FLINK_LANGUAGE}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_REGION: ${AWS_REGION}
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 3
    volumes:
      - /Users/jeffreyjonathanjennings/j3/code_spaces/apache_flink-kickstarter/java/app/build/libs:/opt/flink/java_apps
      - /Users/jeffreyjonathanjennings/j3/code_spaces/apache_flink-kickstarter/python:/opt/flink/python_apps
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - AWS_REGION=$AWS_REGION
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_S3_BUCKET=$AWS_S3_BUCKET
      - FLINK_LANGUAGE=$FLINK_LANGUAGE
