from enum import Enum

__copyright__  = "Copyright (c) 2024 Jeffrey Jonathan Jennings"
__credits__    = ["Jeffrey Jonathan Jennings"]
__license__    = "MIT"
__maintainer__ = "Jeffrey Jonathan Jennings"
__email__      = "j3@thej3.com"
__status__     = "dev"


class ErrorEnum(Enum):
    # Enumerators with their error codes and messages
    ERR_CODE_MISSING_OR_INVALID_FIELD = "ERR_CODE_MISSING_OR_INVALID_FIELD"
    ERR_CODE_IO_EXCEPTION = "ERR_CODE_IO_EXCEPTION"
    ERR_CODE_AWS_REQUESTED_SECRET_DOES_HAVE_NOT_STRING = "ERR_CODE_AWS_REQUESTED_SECRET_DOES_HAVE_NOT_STRING"
    ERR_CODE_AWS_REQUESTED_SECRET_HAS_NO_VALUE = "ERR_CODE_AWS_REQUESTED_SECRET_HAS_NO_VALUE"
    ERR_CODE_AWS_REQUESTED_SECRET_NOT_FOUND = "ERR_CODE_AWS_REQUESTED_SECRET_NOT_FOUND"
    ERR_CODE_AWS_INVALID_REQUEST = "ERR_CODE_AWS_INVALID_REQUEST"
    ERR_CODE_AWS_INVALID_PARAMETERS = "ERR_CODE_AWS_INVALID_PARAMETERS"
    ERR_CODE_AWS_REQUESTED_PARAMETER_PREFIX_NOT_FOUND = "ERR_CODE_AWS_REQUESTED_PARAMETER_PREFIX_NOT_FOUND"
