name: "AWS Environment Info"
description: 'Based on the input of the environment type, the relevant environmental information is provided as output.'
author: 'Jeffrey Jonathan Jennings (J3)'

inputs:
  aws_environment:
    required: true
    description: 'The AWS Environment'
  aws_dev_account_id:
    required: true
    description: 'The AWS Dev Account ID'
  aws_test_account_id:
    required: true
    description: 'The AWS Test Account ID'
  aws_prod_account_id:
    required: true
    description: 'The AWS Prod Account ID'
  aws_region:
    required: true
    description: The AWS Region.
  snowflake_warehouse:
    required: true
    description: The Snowflake Warehouse.
  service_account_user:
    required: true
    description: The Service Account User.
  auto_offset_reset:
    required: false
    description: The Auto Offset Reset.
  number_of_api_keys_to_retain:
    required: false
    description: The Number of API Keys to Retain.
  day_count:
    required: false
    description: The Day Count.
outputs:
  aws_account_id:
    value: ${{ steps.workflow-inputs-output.outputs.AWS_ACCOUNT_ID }}
    description: The AWS Account ID.

runs:
  using: composite
  steps:
    - if: inputs.aws_environment == 'dev'
      name: dev-environment
      shell: bash
      working-directory: ./.github/
      run: echo "AWS_ACCOUNT_ID=${{ inputs.aws_dev_account_id }}" >> $GITHUB_ENV

    - if: inputs.aws_environment == 'test'
      name: test-environment
      shell: bash
      working-directory: ./.github/
      run: echo "AWS_ACCOUNT_ID=${{ inputs.aws_test_account_id }}" >> $GITHUB_ENV

    - if: inputs.aws_environment == 'prod'
      name: prod-environment
      shell: bash
      working-directory: ./.github/
      run: echo "AWS_ACCOUNT_ID=${{ inputs.aws_prod_account_id }}" >> $GITHUB_ENV

    - name: "Display Workflow Inputs"
      shell: bash
      working-directory: ./.github/
      id: workflow-inputs-output
      run: |
        echo "AWS_ACCOUNT_ID=${{ env.AWS_ACCOUNT_ID }}" >> $GITHUB_OUTPUT
        echo "### Workflow Inputs" >> $GITHUB_STEP_SUMMARY
        echo `date` >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "aws_environment  : ${{ inputs.aws_environment }}" >> $GITHUB_STEP_SUMMARY
        echo "aws_account_id   : ${{ env.AWS_ACCOUNT_ID }}" >> $GITHUB_STEP_SUMMARY        
        echo "aws_region       : ${{ inputs.aws_region }}" >> $GITHUB_STEP_SUMMARY
        echo "snowflake_warehouse : ${{ inputs.snowflake_warehouse }}" >> $GITHUB_STEP_SUMMARY
        echo "service_account_user: ${{ inputs.service_account_user }}" >> $GITHUB_STEP_SUMMARY
        echo "number_of_api_keys_to_retain: ${{ inputs.number_of_api_keys_to_retain }}" >> $GITHUB_STEP_SUMMARY
        echo "auto_offset_reset           : ${{ inputs.auto_offset_reset }}" >> $GITHUB_STEP_SUMMARY
        echo "day_count                   : ${{ inputs.day_count }}" >> $GITHUB_STEP_SUMMARY
