/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package kickstarter.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class FlyerStatsAvroData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9167612556607522223L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FlyerStatsAvroData\",\"namespace\":\"kickstarter.model\",\"fields\":[{\"name\":\"email_address\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"total_flight_duration\",\"type\":\"long\"},{\"name\":\"number_of_flights\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FlyerStatsAvroData> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FlyerStatsAvroData> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FlyerStatsAvroData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FlyerStatsAvroData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FlyerStatsAvroData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FlyerStatsAvroData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FlyerStatsAvroData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FlyerStatsAvroData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FlyerStatsAvroData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String email_address;
  private long total_flight_duration;
  private long number_of_flights;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FlyerStatsAvroData() {}

  /**
   * All-args constructor.
   * @param email_address The new value for email_address
   * @param total_flight_duration The new value for total_flight_duration
   * @param number_of_flights The new value for number_of_flights
   */
  public FlyerStatsAvroData(java.lang.String email_address, java.lang.Long total_flight_duration, java.lang.Long number_of_flights) {
    this.email_address = email_address;
    this.total_flight_duration = total_flight_duration;
    this.number_of_flights = number_of_flights;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return email_address;
    case 1: return total_flight_duration;
    case 2: return number_of_flights;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: email_address = value$ != null ? value$.toString() : null; break;
    case 1: total_flight_duration = (java.lang.Long)value$; break;
    case 2: number_of_flights = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'email_address' field.
   * @return The value of the 'email_address' field.
   */
  public java.lang.String getEmailAddress() {
    return email_address;
  }


  /**
   * Sets the value of the 'email_address' field.
   * @param value the value to set.
   */
  public void setEmailAddress(java.lang.String value) {
    this.email_address = value;
  }

  /**
   * Gets the value of the 'total_flight_duration' field.
   * @return The value of the 'total_flight_duration' field.
   */
  public long getTotalFlightDuration() {
    return total_flight_duration;
  }


  /**
   * Sets the value of the 'total_flight_duration' field.
   * @param value the value to set.
   */
  public void setTotalFlightDuration(long value) {
    this.total_flight_duration = value;
  }

  /**
   * Gets the value of the 'number_of_flights' field.
   * @return The value of the 'number_of_flights' field.
   */
  public long getNumberOfFlights() {
    return number_of_flights;
  }


  /**
   * Sets the value of the 'number_of_flights' field.
   * @param value the value to set.
   */
  public void setNumberOfFlights(long value) {
    this.number_of_flights = value;
  }

  /**
   * Creates a new FlyerStatsAvroData RecordBuilder.
   * @return A new FlyerStatsAvroData RecordBuilder
   */
  public static kickstarter.model.FlyerStatsAvroData.Builder newBuilder() {
    return new kickstarter.model.FlyerStatsAvroData.Builder();
  }

  /**
   * Creates a new FlyerStatsAvroData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FlyerStatsAvroData RecordBuilder
   */
  public static kickstarter.model.FlyerStatsAvroData.Builder newBuilder(kickstarter.model.FlyerStatsAvroData.Builder other) {
    if (other == null) {
      return new kickstarter.model.FlyerStatsAvroData.Builder();
    } else {
      return new kickstarter.model.FlyerStatsAvroData.Builder(other);
    }
  }

  /**
   * Creates a new FlyerStatsAvroData RecordBuilder by copying an existing FlyerStatsAvroData instance.
   * @param other The existing instance to copy.
   * @return A new FlyerStatsAvroData RecordBuilder
   */
  public static kickstarter.model.FlyerStatsAvroData.Builder newBuilder(kickstarter.model.FlyerStatsAvroData other) {
    if (other == null) {
      return new kickstarter.model.FlyerStatsAvroData.Builder();
    } else {
      return new kickstarter.model.FlyerStatsAvroData.Builder(other);
    }
  }

  /**
   * RecordBuilder for FlyerStatsAvroData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FlyerStatsAvroData>
    implements org.apache.avro.data.RecordBuilder<FlyerStatsAvroData> {

    private java.lang.String email_address;
    private long total_flight_duration;
    private long number_of_flights;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(kickstarter.model.FlyerStatsAvroData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.email_address)) {
        this.email_address = data().deepCopy(fields()[0].schema(), other.email_address);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.total_flight_duration)) {
        this.total_flight_duration = data().deepCopy(fields()[1].schema(), other.total_flight_duration);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.number_of_flights)) {
        this.number_of_flights = data().deepCopy(fields()[2].schema(), other.number_of_flights);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing FlyerStatsAvroData instance
     * @param other The existing instance to copy.
     */
    private Builder(kickstarter.model.FlyerStatsAvroData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.email_address)) {
        this.email_address = data().deepCopy(fields()[0].schema(), other.email_address);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.total_flight_duration)) {
        this.total_flight_duration = data().deepCopy(fields()[1].schema(), other.total_flight_duration);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.number_of_flights)) {
        this.number_of_flights = data().deepCopy(fields()[2].schema(), other.number_of_flights);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'email_address' field.
      * @return The value.
      */
    public java.lang.String getEmailAddress() {
      return email_address;
    }


    /**
      * Sets the value of the 'email_address' field.
      * @param value The value of 'email_address'.
      * @return This builder.
      */
    public kickstarter.model.FlyerStatsAvroData.Builder setEmailAddress(java.lang.String value) {
      validate(fields()[0], value);
      this.email_address = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'email_address' field has been set.
      * @return True if the 'email_address' field has been set, false otherwise.
      */
    public boolean hasEmailAddress() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'email_address' field.
      * @return This builder.
      */
    public kickstarter.model.FlyerStatsAvroData.Builder clearEmailAddress() {
      email_address = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'total_flight_duration' field.
      * @return The value.
      */
    public long getTotalFlightDuration() {
      return total_flight_duration;
    }


    /**
      * Sets the value of the 'total_flight_duration' field.
      * @param value The value of 'total_flight_duration'.
      * @return This builder.
      */
    public kickstarter.model.FlyerStatsAvroData.Builder setTotalFlightDuration(long value) {
      validate(fields()[1], value);
      this.total_flight_duration = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'total_flight_duration' field has been set.
      * @return True if the 'total_flight_duration' field has been set, false otherwise.
      */
    public boolean hasTotalFlightDuration() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'total_flight_duration' field.
      * @return This builder.
      */
    public kickstarter.model.FlyerStatsAvroData.Builder clearTotalFlightDuration() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'number_of_flights' field.
      * @return The value.
      */
    public long getNumberOfFlights() {
      return number_of_flights;
    }


    /**
      * Sets the value of the 'number_of_flights' field.
      * @param value The value of 'number_of_flights'.
      * @return This builder.
      */
    public kickstarter.model.FlyerStatsAvroData.Builder setNumberOfFlights(long value) {
      validate(fields()[2], value);
      this.number_of_flights = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'number_of_flights' field has been set.
      * @return True if the 'number_of_flights' field has been set, false otherwise.
      */
    public boolean hasNumberOfFlights() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'number_of_flights' field.
      * @return This builder.
      */
    public kickstarter.model.FlyerStatsAvroData.Builder clearNumberOfFlights() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FlyerStatsAvroData build() {
      try {
        FlyerStatsAvroData record = new FlyerStatsAvroData();
        record.email_address = fieldSetFlags()[0] ? this.email_address : (java.lang.String) defaultValue(fields()[0]);
        record.total_flight_duration = fieldSetFlags()[1] ? this.total_flight_duration : (java.lang.Long) defaultValue(fields()[1]);
        record.number_of_flights = fieldSetFlags()[2] ? this.number_of_flights : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FlyerStatsAvroData>
    WRITER$ = (org.apache.avro.io.DatumWriter<FlyerStatsAvroData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FlyerStatsAvroData>
    READER$ = (org.apache.avro.io.DatumReader<FlyerStatsAvroData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.email_address);

    out.writeLong(this.total_flight_duration);

    out.writeLong(this.number_of_flights);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.email_address = in.readString();

      this.total_flight_duration = in.readLong();

      this.number_of_flights = in.readLong();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.email_address = in.readString();
          break;

        case 1:
          this.total_flight_duration = in.readLong();
          break;

        case 2:
          this.number_of_flights = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (email_address == null ? 0 : email_address.hashCode());
    result = 31 * result + Long.hashCode(total_flight_duration);
    result = 31 * result + Long.hashCode(number_of_flights);
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof FlyerStatsAvroData)) {
      return false;
    }
    FlyerStatsAvroData other = (FlyerStatsAvroData) o;
    if (!java.util.Objects.equals(this.email_address, other.email_address)) {
      return false;
    }
    if (this.total_flight_duration != other.total_flight_duration) {
      return false;
    }
    if (this.number_of_flights != other.number_of_flights) {
      return false;
    }
    return true;
  }
}










